# RT-Thread building script for component

import os
import rtconfig
from building import *
Import('SDK_LIB')

cwd = GetCurrentDir()

# add the general drivers.
src = Split("""
board.c
""")

# add serial driver code
if  GetDepend('BSP_USING_UART1') or GetDepend('BSP_USING_UART2'):
    src += ['drv_uart.c']

# add gpio driver code
if  GetDepend(['BSP_USING_GPIO']):
    src += ['drv_gpio.c']

# add adc driver code
if  GetDepend(['BSP_USING_ADC']):
    src += ['drv_adc.c']

# add flash driver code
if  GetDepend(['BSP_USING_OCFLASH']):
    src += ['drv_flash.c']
CPPPATH = [cwd]

startup_path_prefix = SDK_LIB

if rtconfig.PLATFORM in ['gcc']:
    src += [startup_path_prefix + '/MM32F526x/Source/GCC_StartAsm/startup_mm32f5260_gcc.s']
elif rtconfig.PLATFORM in ['armcc', 'armclang']:
    src += [startup_path_prefix + '/MM32F526x/Source/KEIL_StartAsm/startup_mm32f5260_keil.c']
elif rtconfig.PLATFORM in ['iccarm']:
    src += [startup_path_prefix + '/MM32F526x/Source/IAR_StartAsm/startup_mm32f5260_iar.s']

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
